// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarrotController from "./carrot_controller"
application.register("carrot", CarrotController)

import EnergyListController from "./energy_list_controller"
application.register("energy-list", EnergyListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeLoaderController from "./home_loader_controller"
application.register("home-loader", HomeLoaderController)

import MoodsListController from "./moods_list_controller"
application.register("moods-list", MoodsListController)

import SearchLoaderController from "./search_loader_controller"
application.register("search-loader", SearchLoaderController)

import ShoppingMapController from "./shopping_map_controller"
application.register("shopping-map", ShoppingMapController)

import SymptomsListController from "./symptoms_list_controller"
application.register("symptoms-list", SymptomsListController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
